spring:
  application:
    name: ms-sale-report
  profiles:
    default: default
  config:
    import: "optional:configserver:http://localhost:7777"
  data:
    mongodb:
      authentication-database: ${db.authentication-db}
      host: ${db.host}
      port: ${db.port}
      username: ${db.usr}
      password: ${db.pwd}

server:
  port: 1100
  servlet:
    context-path: /api/report/sale

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/